'use client'
import Loader from "@/components/micros/Loader";
import "design-system-react/src/assets/icons/style.css";
import "design-system-react/src/styles/keen-slider.min.css";
import "design-system-react/src/styles/porto-fonts.css";
import { Open_Sans } from "next/font/google";
import React, { useEffect, useState } from "react";
import "./globals.css";


const openSans = Open_Sans({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const [stylesLoaded, setStylesLoaded] = useState<any>(false);

  useEffect(() => {
    const handleStylesLoad = () => {
      setStylesLoaded(true);
    };

    document.addEventListener('DOMContentLoaded', handleStylesLoad);
    window.addEventListener('load', handleStylesLoad);

    return () => {
      document.removeEventListener('DOMContentLoaded', handleStylesLoad);
      window.removeEventListener('load', handleStylesLoad);
      handleStylesLoad();
    };
  }, []);

  return (
    <html lang="en">
      <body className={openSans.className}>
        {stylesLoaded ? children : <Loader />}
      </body>
    </html>
  );
}
